// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzkwzgbujhfozfssegyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6a3d6Z2J1amhmb3pmc3NlZ3lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MjExMDQsImV4cCI6MjA3MDM5NzEwNH0.Krxjpkvl-mw3ISJPquKcx2Nsbd3qsltNfFX8zmYDZRU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});